drop table if exists `USER`;
CREATE TABLE `USER` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `USERID` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '비밀번호(bcrypt)',
  `NAME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `AGE` INT(3),
  PRIMARY KEY  (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;